"""Kanban board: card persistence + the rolled-up human view.

Cards are the durable source of truth (``analysis/studies/<id>/card.yaml``).
The board (``analysis/BOARD.md`` in git; optional ``analysis/board.html`` local)
is a regenerated projection of the cards — never edited by hand.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path
from typing import Dict, List, Optional

import yaml

from . import config
from .model import (
    ATTENTION_LANES,
    Card,
    StudyState,
)

CARD_NAME = "card.yaml"

# Column order for the rolled-up board.
LANE_ORDER: List[StudyState] = [
    StudyState.CONNECTION_DOWN,
    StudyState.ATTENTION,
    StudyState.BUDGET_EXCEEDED,
    StudyState.RUNNING,
    StudyState.DISPATCHED,
    StudyState.COLLECTING,
    StudyState.ANALYZING,
    StudyState.SMOKING,
    StudyState.READY,
    StudyState.APPROVED,
    StudyState.DRAFT,
    StudyState.REPORTED,
    StudyState.DONE,
]

LANE_EMOJI: Dict[StudyState, str] = {
    StudyState.CONNECTION_DOWN: "🔌",
    StudyState.ATTENTION: "⚠️",
    StudyState.BUDGET_EXCEEDED: "💸",
    StudyState.RUNNING: "🏃",
    StudyState.DISPATCHED: "🚀",
    StudyState.COLLECTING: "📥",
    StudyState.ANALYZING: "🔬",
    StudyState.SMOKING: "🧪",
    StudyState.READY: "✅",
    StudyState.APPROVED: "📝",
    StudyState.DRAFT: "✏️",
    StudyState.REPORTED: "📄",
    StudyState.DONE: "🏁",
}


# --------------------------------------------------------------------------
# Card IO
# --------------------------------------------------------------------------


def card_path(study_id: str) -> Path:
    return config.study_dir(study_id) / CARD_NAME


def has_card(study_id: str) -> bool:
    return card_path(study_id).is_file()


def load_card(study_id: str) -> Card:
    path = card_path(study_id)
    if not path.is_file():
        raise FileNotFoundError(f"no card.yaml for study {study_id!r} at {path}")
    raw = yaml.safe_load(path.read_text()) or {}
    return Card.from_dict(raw)


def save_card(card: Card) -> Path:
    """Atomically write card.yaml (temp file + os.replace) so a crash mid-write
    can never corrupt the source of truth."""
    card.touch()
    d = config.study_dir(card.id)
    d.mkdir(parents=True, exist_ok=True)
    path = d / CARD_NAME
    data = yaml.safe_dump(card.to_dict(), sort_keys=False, default_flow_style=False)
    fd, tmp = tempfile.mkstemp(dir=str(d), prefix=".card.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(data)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)
    return path


def list_study_ids() -> List[str]:
    root = config.studies_dir()
    if not root.is_dir():
        return []
    ids = []
    for child in sorted(root.iterdir()):
        if child.is_dir() and (
            (child / CARD_NAME).is_file() or (child / "study.yaml").is_file()
        ):
            ids.append(child.name)
    return ids


def load_all_cards() -> List[Card]:
    cards = []
    for sid in list_study_ids():
        if has_card(sid):
            try:
                cards.append(load_card(sid))
            except Exception:  # a malformed card must not sink the whole board
                continue
    return cards


# --------------------------------------------------------------------------
# Rolled-up view
# --------------------------------------------------------------------------


def _progress_str(card: Card) -> str:
    p = card.progress()
    if p["total"] == 0:
        return "—"
    parts = [f"{p['done']}/{p['total']} done"]
    if p["running"]:
        parts.append(f"{p['running']} R")
    if p["queued"] + p["pending"]:
        parts.append(f"{p['queued'] + p['pending']} PD")
    if p["failed"]:
        parts.append(f"{p['failed']} ✗")
    return ", ".join(parts)


def render_board_md(cards: List[Card]) -> str:
    lines: List[str] = ["# Analysis board", ""]
    lines.append(f"_{len(cards)} studies. Regenerated by `analysis board`; do not edit._")
    lines.append("")

    by_lane: Dict[StudyState, List[Card]] = {}
    for c in cards:
        by_lane.setdefault(c.state, []).append(c)

    # Attention block first, loud, if anything needs eyes.
    attn = [c for c in cards if c.state in ATTENTION_LANES]
    if attn:
        lines.append("## ⚠️ Needs attention")
        lines.append("")
        lines.append("| Study | Lane | Why | Updated |")
        lines.append("|---|---|---|---|")
        for c in attn:
            why = c.attention[-1]["reason"] if c.attention else ""
            lines.append(
                f"| `{_md(c.id)}` | {LANE_EMOJI.get(c.state,'')} {c.state.value} "
                f"| {_md(why)} | {c.updated} |"
            )
        lines.append("")

    for lane in LANE_ORDER:
        if lane in ATTENTION_LANES:
            continue  # already shown above
        group = by_lane.get(lane, [])
        if not group:
            continue
        lines.append(f"## {LANE_EMOJI.get(lane,'')} {lane.value}  ({len(group)})")
        lines.append("")
        lines.append("| Study | Kind | App | Cluster | Progress | Core-h | Updated |")
        lines.append("|---|---|---|---|---|---|---|")
        for c in group:
            ceil = c.budget.ceiling_core_hours
            core = f"{c.budget.spent_core_hours:.1f}"
            if ceil:
                core += f"/{ceil:.0f}"
            lines.append(
                f"| `{_md(c.id)}` | {_md(c.kind)} | {_md(c.app)} | {_md(c.cluster)} | "
                f"{_progress_str(c)} | {core} | {c.updated} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_board_md(cards: Optional[List[Card]] = None) -> Path:
    if cards is None:
        cards = load_all_cards()
    path = config.board_dir() / "BOARD.md"
    path.write_text(render_board_md(cards))
    return path


def refresh(cards: Optional[List[Card]] = None) -> None:
    """Regenerate the human view: an Obsidian Home MOC + study notes when a
    vault is configured, otherwise the plain BOARD.md + board.html."""
    if cards is None:
        cards = load_all_cards()
    if config.vault_root():
        from . import vault  # local import to avoid a cycle (vault imports board)
        vault.sync_vault(cards)
    else:
        write_board_md(cards)
        write_board_html(cards)


def render_board_html(cards: List[Card]) -> str:
    """Minimal self-contained HTML board (local convenience; gitignored)."""
    rows = []
    for c in sorted(cards, key=lambda x: (x.state.value, x.id)):
        p = card_progress_bar(c)
        why = ""
        if c.state in ATTENTION_LANES and c.attention:
            why = c.attention[-1].get("reason", "")
        rows.append(
            f"<tr><td><code>{_escape(c.id)}</code></td>"
            f"<td>{LANE_EMOJI.get(c.state,'')} {_escape(c.state.value)}</td>"
            f"<td>{_escape(c.kind)}</td><td>{_escape(c.app)}</td><td>{_escape(c.cluster)}</td>"
            f"<td>{p}</td><td>{_escape(why)}</td><td>{_escape(c.updated)}</td></tr>"
        )
    body = "\n".join(rows)
    return f"""<!doctype html>
<meta charset="utf-8"><title>Analysis board</title>
<style>
  body{{font:14px system-ui,sans-serif;margin:2rem;color:#222;background:#fafafa}}
  table{{border-collapse:collapse;width:100%}}
  th,td{{padding:.4rem .6rem;border-bottom:1px solid #ddd;text-align:left}}
  th{{background:#eee}} code{{background:#eee;padding:.1rem .3rem;border-radius:3px}}
</style>
<h1>Analysis board</h1>
<p>{len(cards)} studies. Regenerated by <code>analysis board</code>.</p>
<table><thead><tr>
<th>Study</th><th>Lane</th><th>Kind</th><th>App</th><th>Cluster</th>
<th>Progress</th><th>Attention</th><th>Updated</th>
</tr></thead><tbody>
{body}
</tbody></table>
"""


def card_progress_bar(c: Card) -> str:
    return _escape(_progress_str(c))


def write_board_html(cards: Optional[List[Card]] = None) -> Path:
    if cards is None:
        cards = load_all_cards()
    path = config.analysis_dir() / "board.html"
    path.write_text(render_board_html(cards))
    return path


def _escape(s: str) -> str:
    return (
        str(s)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _md(s: str) -> str:
    """Sanitize free text for a GFM table cell: escape pipes/backticks and
    collapse newlines, so diagnostic output can't shift or duplicate columns."""
    return (
        str(s)
        .replace("\\", "\\\\")
        .replace("|", "\\|")
        .replace("`", "\\`")
        .replace("\r", " ")
        .replace("\n", " ")
    )
