"""Obsidian vault projection: a Home MOC + one note per study, generated from
cards.

One-way only: ``card.yaml`` is the source of truth; these notes are regenerated
and must not be hand-edited for state (edit prose/learnings freely — the
generator only owns the frontmatter and the generated sections). Runs when
``$ANALYSIS_VAULT`` is configured; otherwise the plain ``BOARD.md`` is used.
"""

from __future__ import annotations

from pathlib import Path
from typing import List

from . import config
from .board import LANE_EMOJI, LANE_ORDER, _md, _progress_str
from .model import ATTENTION_LANES, Card


def _ceiling_str(card: Card) -> str:
    ceil = card.budget.ceiling_core_hours
    base = f"{card.budget.spent_core_hours:.1f}"
    return base + (f" / {ceil:.0f}" if ceil is not None else "")


def _frontmatter(card: Card) -> str:
    ceil = card.budget.ceiling_core_hours
    p = card.progress()
    return "\n".join([
        "---",
        f"id: {card.id}",
        f"kind: {card.kind}",
        f"app: {card.app}",
        f"cluster: {card.cluster}",
        f"state: {card.state.value}",
        f"core_hours: {card.budget.spent_core_hours}",
        f"core_hours_ceiling: {ceil if ceil is not None else ''}",
        f"cases_total: {p['total']}",
        f"cases_done: {p['done']}",
        f"updated: {card.updated}",
        "tags: [analysis-study]",
        "---",
    ])


def write_study_note(card: Card) -> Path:
    d = config.study_dir(card.id)
    d.mkdir(parents=True, exist_ok=True)
    note = d / f"{card.id}.md"

    body: List[str] = [_frontmatter(card)]
    body.append(f"# {card.title or card.id}")
    body.append(f"[[Home]] · **{card.state.value}** · {_progress_str(card)}")
    body.append("")

    body.append("## Workspaces")
    body.append("- Report: [report.html](results/report.html)")
    body.append("- Spec: [study.yaml](study.yaml)")
    if card.remote_workdir:
        body.append(f"- HPC workdir: `{card.cluster}:{card.remote_workdir}`")
    if card.binary_path:
        body.append(f"- Binary: `{card.binary_path}`")
    body.append("")

    body.append("## Provenance")
    body.append(
        f"- app `{card.app}` · sha `{card.repo_sha or '—'}` · "
        f"cluster `{card.cluster}` · account `{card.account}`"
    )
    body.append(f"- core-hours: {_ceiling_str(card)}")
    body.append("")

    if card.attention:
        body.append("## ⚠️ Attention")
        for a in card.attention[-15:]:
            body.append(f"- {_md(a.get('reason', ''))}")
        body.append("")

    body.append("## Learnings")
    body.append(
        "_Link learnings that cite this study, e.g. "
        "`[[thermomech-preconditioner]]`. Learnings live in `learnings/`._"
    )
    body.append("")
    note.write_text("\n".join(body) + "\n")
    return note


def write_home(cards: List[Card]) -> Path:
    home = config.board_dir() / "Home.md"
    lines: List[str] = [
        "# Analysis vault",
        "",
        f"_{len(cards)} studies. Home / map of content — regenerated by "
        "`analysis board`. Edit study notes, not this file._",
        "",
    ]

    attn = [c for c in cards if c.state in ATTENTION_LANES]
    if attn:
        lines += ["## ⚠️ Needs attention", ""]
        for c in attn:
            why = c.attention[-1]["reason"] if c.attention else ""
            lines.append(
                f"- [[{c.id}]] — {LANE_EMOJI.get(c.state,'')} {c.state.value} — {_md(why)}"
            )
        lines.append("")

    for lane in LANE_ORDER:
        if lane in ATTENTION_LANES:
            continue
        group = [c for c in cards if c.state == lane]
        if not group:
            continue
        lines += [f"## {LANE_EMOJI.get(lane,'')} {lane.value} ({len(group)})", ""]
        for c in group:
            lines.append(f"- [[{c.id}]] — {c.kind}/{c.app} — {_progress_str(c)}")
        lines.append("")

    lines += [
        "## Learnings",
        "",
        "Distilled, evidence-linked findings live in `learnings/`. Each cites the "
        "studies that support it.",
        "",
    ]
    home.write_text("\n".join(lines) + "\n")
    return home


def sync_vault(cards: List[Card]) -> None:
    write_home(cards)
    for c in cards:
        write_study_note(c)
